{% set version = "1.13.0" %}

package:
  name: spdlog
  version: {{ version }}

source:
  url: https://github.com/gabime/spdlog/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 534f2ee1a4dcbeb22249856edfb2be76a1cf4f708a20b0ac2ed090ee24cfdbc9

build:
  number: 0

requirements:
  build:
    - cmake
    {% if win %}  # do nothing
    {% else %}
    - make
    {% endif %}
    - {{ compiler('cxx') }}
  host:
    - fmt
  run:
    - fmt

about:
  home: https://github.com/gabime/spdlog
  license: MIT
  summary: "Very fast, header-only/compiled, C++ logging library."

extra:
  recipe-maintainers:
    - saldoran
